version: "2.1"
services:
  pipeline:
    image: nota/pipeline-mod-nota:v1.11.1_v1.3.4
    environment:
      PIPELINE2_WS_HOST: "0.0.0.0"
      PIPELINE2_WS_AUTHENTICATION: "false"
    ports:
      - "8181:8181"
    volumes:
      - "pipeline-data:/opt/daisy-pipeline2/data"
  webui:
    image: daisyorg/pipeline-webui
    environment:
      DAISY_PIPELINE2_URL: http://pipeline:8181/ws
    ports:
      - "9000:9000"
    volumes:
      - "webui-data:/opt/daisy-pipeline2-webui/data"
    depends_on:
      pipeline:
        condition: service_healthy
volumes:
  pipeline-data:
  webui-data: